name: Publish package to the Github Repository

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PROJECT: 'samples-dotnet-helloworld/samples-dotnet-helloworld.csproj'
  BUILD_CONFIG: 'Release'

jobs:
  Release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Set up NuGet
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: 4.8
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      id: semantic
      
    - name: Restore Packages
      if: steps.semantic.outputs.new_release_published == 'true'
      run: nuget restore

    - name: Build Package
      if: steps.semantic.outputs.new_release_published == 'true'
      working-directory: samples-dotnet-helloworld
      run: nuget pack HelloWorld.nuspec -Version ${{ steps.semantic.outputs.new_release_version }}

    - name: Publish the Package to nuget.org
      if: steps.semantic.outputs.new_release_published == 'true'
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json'



      